import { Injectable, inject } from '@angular/core';
import { AuthService } from './auth.service';

@Injectable({
  providedIn: 'root',
})
export class SidebarService {
  private authService = inject(AuthService);
  menu: any[] = [];

  get onLoadMenu() {
    return (this.menu = [
      {
        id: 1,
        visible: this.authService.onValidateRoles(['SuperUsuario']),
        label: 'Configuración',
        icon: 'fa-thin fa-gear',
        link: 'configuracion/panel',
      },
      {
        id: 1,
        visible: this.authService.onValidateRoles(['Residente']),
        label: 'Accesos',
        icon: 'fa-thin fa-key',
        link: 'accounts/cliente',
      },
      {
        id: 17,
        visible: this.authService.onValidateRoles([
          'Asistente',
          'GerenteMantenimiento',
          'Mantenimiento',
          'Residente',
          'Sistemas',
          'SuperUsuario',
          'SupervisionOperativa',
        ]),
        label: 'Mi Edificio',
        icon: 'fa-thin fa-building',
        link: 'operaciones/mi-edificio',
        parentId: 16,
      },
      {
        id: 1,
        visible: this.authService.onValidateRoles(['Legal', 'SuperUsuario']),
        label: '1.-Legal',
        icon: 'fa-thin fa-gavel',
        subItems: [
          {
            id: 24,
            visible: this.authService.onValidateRoles([
              'Legal',
              'SuperUsuario',
            ]),
            label: 'Minutas',
            link: 'contabilidad/pendientes-minutas-legal',
            parentId: 16,
          },
        ],
      },
      {
        id: 1,
        visible: this.authService.onValidateRoles([
          'Contador',
          'SuperUsuario',
          'SupervisorContable',
        ]),
        label: '2.-Contabilidad',
        icon: 'fa-thin fa-hand-holding-dollar',
        subItems: [
          {
            id: 24,
            visible: this.authService.onValidateRoles([
              'Contador',
              'SuperUsuario',
              'SupervisorContable',
            ]),
            label: 'Presentaciones',
            link: 'operaciones/presentacion-junta-comite/presentaciones',
            parentId: 16,
          },
          {
            id: 24,
            visible: this.authService.onValidateRoles([
              'Contador',
              'SuperUsuario',
            ]),
            label: 'Minutas',
            link: 'contabilidad/pendientes-minutas',
            parentId: 16,
          },
          {
            id: 24,
            visible: this.authService.onValidateRoles([
              'Contador',
              'SuperUsuario',
            ]),
            label: 'Presupuesto',
            link: 'operaciones/compras/cedula-cliente',
            parentId: 16,
          },
        ],
      },
      {
        id: 3,
        visible: this.authService.onValidateRoles([
          'Direccion',
          'GerenteMantenimiento',
          'SuperUsuario',
          'SupervisionOperativa',
        ]),
        label: '3.-Op-Supervisión',
        icon: 'fa-thin fa-user-tie',
        subItems: [
          {
            id: 4,
            visible: this.authService.onValidateRoles([
              'Direccion',
              'GerenteMantenimiento',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),
            label: 'Bitácora Diaria',
            link: '/supervision/bitacora-diaria',
            parentId: 3,
          },
          {
            id: 5,
            visible: this.authService.onValidateRoles([
              'Direccion',
              'GerenteMantenimiento',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),
            label: 'Resultado General',
            link: '/supervision/resultado-general-dashboard',
            parentId: 3,
          },
          {
            id: 5,
            visible: this.authService.onValidateRoles([
              'Direccion',
              'GerenteMantenimiento',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),
            label: 'Reporte Presentaciones',
            link: '/supervision/presentaciones-juntas-comite',
            parentId: 3,
          },
          {
            id: 5,
            visible: this.authService.onValidateRoles([
              'Direccion',
              'GerenteMantenimiento',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),
            label: 'Reporte Minutas',
            link: '/supervision/minutas-resumen',
            parentId: 3,
          },
          {
            id: 5,
            visible: this.authService.onValidateRoles([
              'Direccion',
              'GerenteMantenimiento',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),
            label: 'Reporte Ticket',
            link: '/supervision/reporte-tickets',
            parentId: 3,
          },
          {
            id: 4,
            visible: this.authService.onValidateRoles([
              'GerenteMantenimiento',
              'SuperUsuario',
            ]),
            label: 'Entrega Recepción',
            subItems: [
              {
                id: 5,
                visible: this.authService.onValidateRoles([
                  'GerenteMantenimiento',
                  'SuperUsuario',
                ]),
                label: 'General',
                link: 'entrega-recepcion/general',
                parentId: 3,
              },
              {
                id: 5,
                visible: this.authService.onValidateRoles([
                  'GerenteMantenimiento',
                  'SuperUsuario',
                ]),
                label: 'Equipos',
                link: 'operaciones/entrega-recepcion/equipos',
                parentId: 3,
              },
              {
                id: 5,
                visible: this.authService.onValidateRoles([
                  'GerenteMantenimiento',
                  'SuperUsuario',
                ]),
                label: 'Instalaciones',
                link: 'operaciones/entrega-recepcion/instalaciones',
                parentId: 3,
              },
              {
                id: 5,
                visible: this.authService.onValidateRoles([
                  'GerenteMantenimiento',
                  'SuperUsuario',
                ]),
                label: 'Extintores',
                link: 'operaciones/entrega-recepcion/hidrantes',
                parentId: 3,
              },
              {
                id: 5,
                visible: this.authService.onValidateRoles([
                  'GerenteMantenimiento',
                  'SuperUsuario',
                ]),
                label: 'Llaves',
                link: 'operaciones/entrega-recepcion/llaves',
                parentId: 3,
              },
              {
                id: 5,
                visible: this.authService.onValidateRoles([
                  'GerenteMantenimiento',
                  'SuperUsuario',
                ]),
                label: 'Herramientas',
                link: 'operaciones/entrega-recepcion/herramientas',
                parentId: 3,
              },
              {
                id: 5,
                visible: this.authService.onValidateRoles([
                  'GerenteMantenimiento',
                  'SuperUsuario',
                ]),
                label: 'Mantenimientos',
                link: 'operaciones/entrega-recepcion/mantenimientos',
                parentId: 3,
              },
              {
                id: 5,
                visible: this.authService.onValidateRoles([
                  'GerenteMantenimiento',
                  'SuperUsuario',
                ]),
                label: 'Pendientes',
                link: 'operaciones/entrega-recepcion/mantenimientos-pendientes',
                parentId: 3,
              },
              {
                id: 5,
                visible: this.authService.onValidateRoles([
                  'GerenteMantenimiento',
                  'SuperUsuario',
                ]),
                label: 'Organigrama',
                link: 'operaciones/entrega-recepcion/organigrama',
                parentId: 3,
              },
              {
                id: 5,
                visible: this.authService.onValidateRoles([
                  'GerenteMantenimiento',
                  'SuperUsuario',
                ]),
                label: 'Planos',
                link: 'operaciones/entrega-recepcion/planos',
                parentId: 3,
              },
              {
                id: 5,
                visible: this.authService.onValidateRoles([
                  'GerenteMantenimiento',
                  'SuperUsuario',
                ]),
                label: 'Insumos',
                link: 'operaciones/entrega-recepcion/insumos',
                parentId: 3,
              },
            ],
          },
        ],
      },
      {
        id: 1,
        visible: this.authService.onValidateRoles(['Sistemas', 'SuperUsuario']),
        label: '4.-Sistemas',
        icon: 'fa-thin fa-laptop-code',
        subItems: [
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'Sistemas',
              'SuperUsuario',
            ]),
            label: 'Tickets',
            link: 'sistemas/reportes',
            parentId: 16,
          },
        ],
      },

      {
        id: 1,
        visible: this.authService.onValidateRoles([
          'Asistente',
          'Colaborador',
          'Direccion',
          'GerenteMantenimiento',
          'Mantenimiento',
          'Residente',
          'SuperUsuario',
          'SupervisionOperativa',
        ]),
        label: '5.1-Operaciones',
        icon: 'fa-thin fa-person-chalkboard',
        subItems: [
          {
            id: 1,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'Direccion',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),
            label: 'Resumen',
            link: 'inicio/dashboard',
          },
          {
            id: 17,

            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Residente',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),
            label: 'Presentacion JC',
            link: 'operaciones/presentacion-junta-comite/presentaciones',
            parentId: 16,
          },
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Residente',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),
            label: 'Minutas',
            link: 'operaciones/junta-comite/minutas',
            parentId: 16,
          },
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'GerenteMantenimiento',
              'Mantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Mtto Preventivo',
            link: 'reporte/mantenimiento-preventivo',
            parentId: 16,
          },
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'Colaborador',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),

            label: 'Tickets',
            link: 'operaciones/reporte/tiket-mantenimiento',
            parentId: 16,
          },
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),

            label: 'Reportes',
            link: 'operaciones/reportes-mantenimiento/panel',
            parentId: 16,
          },
        ],
      },
      {
        id: 1,
        visible: this.authService.onValidateRoles([
          'SuperUsuario',
          'Mantenimiento',
          'Asistente',
          'Mantenimiento',
          'Residente',
        ]),
        label: '5.2-Compras',
        icon: 'fa-thin fa-bag-shopping',
        subItems: [
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'SuperUsuario',
              'Asistente',
              'Mantenimiento',
              'Residente',
            ]),
            label: 'Presupuesto',
            link: 'operaciones/compras/cedula-cliente',
            parentId: 16,
          },
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'SuperUsuario',
              'Asistente',
              'Mantenimiento',
              'Residente',
            ]),

            label: 'Productos y servicios',
            link: 'mantenimiento/catalogo/productos-servicios',
            parentId: 16,
          },
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'SuperUsuario',
              'Asistente',
              'Mantenimiento',
              'Residente',
            ]),
            label: 'Solicitud compra',
            link: 'operaciones/compras/solicitudes-compra',
            parentId: 16,
          },
          {
            id: 24,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'Residente',
              'SuperUsuario',
              'Mantenimiento',
            ]),
            label: 'OC Fijos',
            link: 'operaciones/compras/ordenes-compra-fijos',
            parentId: 16,
          },
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'Residente',
              'SuperUsuario',
              'Mantenimiento',
            ]),
            label: 'OC Variables',
            link: 'operaciones/compras/ordenes-compra',
            parentId: 16,
          },
          {
            id: 24,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Catalogo OC Fijos',
            link: 'operaciones/compras/catalogo-gastos-fijos',
            parentId: 16,
          },
          {
            id: 24,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'OC Pagadas',
            link: 'operaciones/compras/pagadas',
            parentId: 16,
          },
        ],
      },
      {
        id: 1,
        visible: this.authService.onValidateRoles([
          'SuperUsuario',
          'Colaborador',
          'GerenteMantenimiento',
          'Mantenimiento',
          'Residente',
        ]),
        label: '5.3-Bitacoras Mtto',
        icon: 'fa-thin fa-book',
        subItems: [
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'SuperUsuario',
              'Colaborador',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
            ]),
            label: 'Recorrido diario',
            link: 'mantenimiento/bitacora/recorrido',
            parentId: 16,
          },
          // {
          //   id: 18,
          //   visible: this.authService.onValidateRoles([
          //     'SuperUsuario',
          //     'Colaborador',
          //     'GerenteMantenimiento',
          //     'Mantenimiento',
          //     'Residente',
          //   ]),
          //   label: 'Recorrido semanal',
          //   link: 'pages/coming-soon',
          //   parentId: 16,
          // },
          // {
          //   id: 18,
          //   visible: this.authService.onValidateRoles([
          //     'SuperUsuario',
          //     'Mantenimiento',
          //     'GerenteMantenimiento',
          //     'Mantenimiento',
          //     'Residente',
          //   ]),
          //   label: '--Mtto correctivo',
          //   link: 'pages/coming-soon',
          //   parentId: 16,
          // },
          // {
          //   id: 18,
          //   visible: this.authService.onValidateRoles([
          //     'SuperUsuario',
          //     'Mantenimiento',
          //     'GerenteMantenimiento',
          //     'Mantenimiento',
          //     'Residente',
          //   ]),
          //   label: '--Mtto preventivo',
          //   link: 'pages/coming-soon',
          //   parentId: 16,
          // },
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'Colaborador',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Consumos lecturas',
            link: 'mantenimiento/bitacora/lista-medidor',
            parentId: 16,
          },
          // {
          //   id: 18,
          //   visible: this.authService.onValidateRoles([
          //     'Colaborador',
          //     'GerenteMantenimiento',
          //     'Mantenimiento',
          //     'Residente',
          //     'SuperUsuario',
          //   ]),
          //   label: 'Consumo de agua',
          //   link: 'pages/coming-soon',
          //   parentId: 16,
          // },
          // {
          //   id: 18,
          //   visible: this.authService.onValidateRoles([
          //     'Colaborador',
          //     'GerenteMantenimiento',
          //     'Mantenimiento',
          //     'Residente',
          //     'SuperUsuario',
          //   ]),
          //   label: 'Consumo de electricidad',
          //   link: 'pages/coming-soon',
          //   parentId: 16,
          // },
          // {
          //   id: 18,
          //   visible: this.authService.onValidateRoles([
          //     'Colaborador',
          //     'GerenteMantenimiento',
          //     'Mantenimiento',
          //     'Residente',
          //     'SuperUsuario',
          //   ]),
          //   label: 'Consumo de gas',
          //   link: 'pages/coming-soon',
          //   parentId: 16,
          // },
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'Colaborador',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Albercas',
            link: 'mantenimiento/bitacora/piscina',
            parentId: 16,
          },
          // {
          //   id: 18,
          //   visible: this.authService.onValidateRoles([
          //     'Colaborador',
          //     'GerenteMantenimiento',
          //     'Mantenimiento',
          //     'Residente',
          //     'SuperUsuario',
          //   ]),
          //   label: '--PCI',
          //   link: 'pages/coming-soon',
          //   parentId: 16,
          // },
          // {
          //   id: 18,
          //   visible: this.authService.onValidateRoles([
          //     'Colaborador',
          //     'GerenteMantenimiento',
          //     'Mantenimiento',
          //     'Residente',
          //     'SuperUsuario',
          //   ]),
          //   label: '--Planta de emergencia',
          //   link: 'pages/coming-soon',
          //   parentId: 16,
          // },
          // {
          //   id: 18,
          //   visible: this.authService.onValidateRoles([
          //     'Colaborador',
          //     'GerenteMantenimiento',
          //     'Mantenimiento',
          //     'Residente',
          //     'SuperUsuario',
          //   ]),
          //   label: '--PTAR',
          //   link: 'pages/coming-soon',
          //   parentId: 16,
          // },
        ],
      },

      {
        id: 1,
        visible: this.authService.onValidateRoles([
          'Asistente',
          'Colaborador',
          'GerenteMantenimiento',
          'Mantenimiento',
          'Residente',
          'Sistemas',
          'SuperUsuario',
        ]),
        label: '5.4-Inventarios',
        icon: 'fa-thin fa-boxes-stacked',
        subItems: [
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Amenidades',
            link: 'mantenimiento/inventario/equipos/2',
            parentId: 16,
          },

          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Áreas Comunes',
            link: 'mantenimiento/inventario/equipos/8',
            parentId: 16,
          },
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Cuartos de Maquinas',
            link: 'mantenimiento/inventario/equipos/7',
            parentId: 16,
          },
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Mobiliario',
            link: 'mantenimiento/inventario/equipos/3',
            parentId: 16,
          },
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Llaves',
            link: 'mantenimiento/inventario/llaves',
            parentId: 16,
          },
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Herramientas',
            link: 'mantenimiento/inventario/herramienta',
            parentId: 16,
          },
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Radios',
            link: 'mantenimiento/inventario/radios',
            parentId: 16,
          },
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'Sistemas',
              'SuperUsuario',
            ]),
            label: 'EQ. Sistemas',
            link: 'mantenimiento/inventario/equipos/6',
            parentId: 16,
          },
          // {
          //   id: 18,
          //   visible: this.authService.onValidateRoles([
          //     'GerenteMantenimiento',
          //     'Mantenimiento',
          //     'Residente',
          //     'SuperUsuario',
          //   ]),
          //   label: '--Medidores de agua',
          //   link: 'pages/coming-soon',
          //   parentId: 16,
          // },
          // {
          //   id: 18,
          //   visible: this.authService.onValidateRoles([
          //     'GerenteMantenimiento',
          //     'Mantenimiento',
          //     'Residente',
          //     'SuperUsuario',
          //   ]),
          //   label: '--Medidores de electricidad',
          //   link: 'pages/coming-soon',
          //   parentId: 16,
          // },
          // {
          //   id: 18,
          //   visible: this.authService.onValidateRoles([
          //     'GerenteMantenimiento',
          //     'Mantenimiento',
          //     'Residente',
          //     'SuperUsuario',
          //   ]),
          //   label: '--Medidores de gas',
          //   link: 'pages/coming-soon',
          //   parentId: 16,
          // },
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Equipos electromecánicos',
            link: 'mantenimiento/inventario/equipos/1',
            parentId: 16,
          },
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Equipos de Gimnasio',
            link: 'mantenimiento/inventario/equipos/5',
            parentId: 16,
          },
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Extintores',
            link: 'mantenimiento/catalogo/extintores',
            parentId: 16,
          },
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'EQ. Iluminación',
            link: 'mantenimiento/catalogo/iluminacion',
            parentId: 16,
          },
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Pintura Especificación',
            link: 'mantenimiento/catalogo/pintura',
            parentId: 16,
          },
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Almacén',
            link: 'mantenimiento/almacen/inventario-productos',
            parentId: 16,
          },
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: '5.4.1-Mov. al almacén',
            subItems: [
              {
                id: 18,
                visible: this.authService.onValidateRoles([
                  'Asistente',
                  'GerenteMantenimiento',
                  'Mantenimiento',
                  'Residente',
                  'SuperUsuario',
                ]),
                label: 'Entradas de insumos',
                link: 'mantenimiento/almacen/entrada-productos',
                parentId: 16,
              },
              {
                id: 18,
                visible: this.authService.onValidateRoles([
                  'Asistente',
                  'GerenteMantenimiento',
                  'Mantenimiento',
                  'Residente',
                  'SuperUsuario',
                ]),
                label: 'Salidas de insumos',
                link: 'mantenimiento/almacen/salida-productos',
                parentId: 16,
              },
              {
                id: 18,
                visible: this.authService.onValidateRoles([
                  'GerenteMantenimiento',
                  'Mantenimiento',
                  'Residente',
                  'SuperUsuario',
                ]),
                label: 'Préstamo de herramientas',
                link: 'mantenimiento/bitacora/prestamo-herramienta',
                parentId: 16,
              },
            ],
          },
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Polizas de Mtto',
            link: 'documento/poliza',
            parentId: 16,
          },
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Documentos',
            link: 'documento/documento',
            parentId: 16,
          },
        ],
      },
      {
        id: 4,
        visible: this.authService.onValidateRoles([
          'Asistente',
          'GerenteMantenimiento',
          'Mantenimiento',
          'Residente',
          'SuperUsuario',
          'SupervisionOperativa',
        ]),
        label: '5.5-Capacitación',
        icon: 'fa-thin fa-book-open-reader',
        subItems: [
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Nomenclatura',
            link: 'capacitacion/nomenclatura',
            parentId: 16,
          },
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),
            label: 'Manuales y procesos',
            link: 'capacitacion/procesos',
            parentId: 16,
          },
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),
            label: 'Formatos',
            link: 'capacitacion/formatos',
            parentId: 16,
          },
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),
            label: 'Comunicados internos',
            link: 'capacitacion/comunicado',
            parentId: 16,
          },
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),
            label: 'Mttos Preventivos',
            link: 'operaciones/calendario/mantenimiento-master',
            parentId: 16,
          },
          {
            id: 17,
            visible: this.authService.onValidateRoles(['SuperUsuario']),
            label: 'Calendario Maestro Equipo',
            link: 'operaciones/calendario/calendario-maestro-equipo',
            parentId: 16,
          },
        ],
      },
      {
        id: 2,
        visible: this.authService.onValidateRoles([
          'Asistente',
          'GerenteMantenimiento',
          'Mantenimiento',
          'Residente',
          'SuperUsuario',
          'SupervisionOperativa',
        ]),
        label: '5.6-Calendarios',
        icon: 'fa-thin fa-calendar-days',
        subItems: [
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'Contador',
              'Residente',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),
            label: 'Fondeos',
            link: 'operaciones/calendario/fondeos',
            parentId: 16,
          },
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Mtto Preventivo',
            link: 'mantenimiento/calendario-anual',
            parentId: 16,
          },
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),
            label: 'Fiestas Judías',
            link: 'operaciones/calendario/fiestas-judias',
            parentId: 16,
          },
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),
            label: 'Fiestas Catolicas',
            link: 'operaciones/calendario/fiestas-cristianas',
            parentId: 16,
          },
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'Contador',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),
            label: 'Cumpleaños',
            link: 'operaciones/calendario/cumpleanos',
            parentId: 16,
          },
        ],
      },
      {
        id: 2,
        visible: this.authService.onValidateRoles(['SuperUsuario']),
        label: '5.7 Comunicados',
        icon: 'fa-thin fa-file-pdf',
        subItems: [
          {
            id: 17,
            visible: this.authService.onValidateRoles(['SuperUsuario']),
            label: 'Enviar Email',
            link: 'comunicacion/enviar-comunicado',
            parentId: 16,
          },
        ],
      },
      {
        id: 17,
        visible: this.authService.onValidateRoles([
          'Asistente',
          'GerenteMantenimiento',
          'Mantenimiento',
          'Residente',
          'SuperUsuario',
          'SupervisionOperativa',
        ]),
        label: '6.1-Directorios',
        icon: 'fa-thin fa-address-book',
        subItems: [
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Organigrama',
            link: 'directorio/organigrama-interno',
            parentId: 16,
          },
          // {
          //   id: 18,
          //   visible: this.authService.onValidateRoles([
          //     'Asistente',
          //     'GerenteMantenimiento',
          //     'RecursosHumanos',
          //     'Residente',
          //     'SuperUsuario',
          //   ]),
          //   label: 'Vacantes',
          //   link: 'reclutamiento/plantilla-interna',
          //   parentId: 16,
          // },
          {
            id: 18,
            visible: this.authService.onValidateRoles(['SuperUsuario']),
            label: 'Clientes',
            link: 'configuracion/clientes',
            parentId: 16,
          },
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),
            label: 'Propiedades',
            link: 'directorio/propiedades',
            parentId: 16,
          },
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),
            label: 'Condominos',
            link: 'directorio/condominos',
            parentId: 16,
          },
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),
            label: 'Comité de vigilancia',
            link: 'directorio/comite-vigilancia',
            parentId: 16,
          },

          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Personal Interno',
            link: 'directorio/empleados/interno',
            parentId: 16,
          },
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),
            label: 'Proveedores',
            link: 'directorio/proveedor',
            parentId: 16,
          },
          // {
          //   id: 18,
          //   visible:
          //     this.SuperUsuario ||
          //     this.Mantenimiento ||
          //     this.SupervisionOperativa ||
          //     this.Residente ||
          //     this.Asistente ||
          //     this.GerenteMantenimiento,
          //   label: 'Mis Proveedores',
          //   link: 'directorio/mi-proveedor',
          //   parentId: 16,
          // },
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Personal Externo',
            link: 'directorio/empleados/externo',
            parentId: 16,
          },
          {
            id: 18,
            visible: this.authService.onValidateRoles(['SuperUsuario']),
            label: 'Personal General',
            link: 'directorio/empleados-general',
            parentId: 16,
          },
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'GerenteMantenimiento',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),
            label: 'Emergencias',
            link: 'directorio/telefonos-emergencia',
            parentId: 16,
          },
        ],
      },
      {
        id: 17,
        visible: this.authService.onValidateRoles([
          'Asistente',
          'Mantenimiento',
          'Residente',
          'SuperUsuario',
        ]),
        label: '6.2-Utilidades',
        icon: 'fa-thin fa-screwdriver-wrench',
        subItems: [
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'Mantenimiento',
              'Residente',
              'SuperUsuario',
            ]),
            label: 'Calculadora IVA',
            link: 'utilidades/calcular-iva',
            parentId: 16,
          },
        ],
      },
      {
        id: 17,
        visible: this.authService.onValidateRoles([
          'Asistente',
          'Residente',
          'SuperUsuario',
          'Reclutamiento',
        ]),
        label: '7.0 Reclutamiento',
        icon: 'fa-thin fa-arrows-down-to-people',
        subItems: [
          {
            id: 18,
            visible: this.authService.onValidateRoles([
              'Asistente',
              'Residente',
              'SuperUsuario',
              'SupervisionOperativa',
            ]),
            label: 'Plantilla',
            link: 'reclutamiento/plantilla-interna',
            parentId: 16,
          },
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'SuperUsuario',
              'Reclutamiento',
            ]),
            label: 'Solicitudes',
            link: 'reclutamiento/solicitudes/vacantes',
            parentId: 16,
          },

          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'SuperUsuario',
              'Reclutamiento',
            ]),
            label: 'Departamentos',
            link: 'reclutamiento/departamentos',
            parentId: 16,
          },
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'SuperUsuario',
              'Reclutamiento',
            ]),
            label: 'Profesiones',
            link: 'reclutamiento/profesiones',
            parentId: 16,
          },
          {
            id: 17,
            visible: this.authService.onValidateRoles([
              'SuperUsuario',
              'Reclutamiento',
            ]),
            label: 'Candidatos',
            link: 'reclutamiento/candidatos',
            parentId: 16,
          },
        ],
      },
      {
        id: 1,
        visible: true,
        label: 'Salir',
        icon: 'fa-thin fa-right-from-bracket',
        link: 'auth/login',
      },
    ]);
  }
}
