export enum EAreaResponsable {
  'Administración',
  'Mantenimiento',
  'Limpieza',
  'Seguridad Interna',
  'SeguridadInterna',
  'Seguridad Externa',
  'SeguridadExterna',
  'Jardineria',
  'Valet Parking',
  'ValetParkig',
  'Conserjería',
  'Externo',
  'Ludoteca',
  'Sistemas',
}
